In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
df = pd.read_csv("../data/Speed Dating Data.csv", encoding="ISO-8859-1")

# Keep only columns with 80% of non-NA values
THRESHOLD = 0.8
df = df.dropna(thresh=df.shape[0]*THRESHOLD, axis=1)

In [11]:
df

,iid,id,gender,idg,condtn,wave,round,position,order,partner,...,sinc1_2,intel1_2,fun1_2,amb1_2,shar1_2,attr3_2,sinc3_2,intel3_2,fun3_2,amb3_2
0,1,1.0,0,1,1,1,10,7,4,1,...,16.67,13.89,22.22,11.11,16.67,6.0,7.0,8.0,7.0,6.0
1,1,1.0,0,1,1,1,10,7,3,2,...,16.67,13.89,22.22,11.11,16.67,6.0,7.0,8.0,7.0,6.0
2,1,1.0,0,1,1,1,10,7,10,3,...,16.67,13.89,22.22,11.11,16.67,6.0,7.0,8.0,7.0,6.0
3,1,1.0,0,1,1,1,10,7,5,4,...,16.67,13.89,22.22,11.11,16.67,6.0,7.0,8.0,7.0,6.0
4,1,1.0,0,1,1,1,10,7,7,5,...,16.67,13.89,22.22,11.11,16.67,6.0,7.0,8.0,7.0,6.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8373,552,22.0,1,44,2,21,22,14,5,18,...,0.00,15.00,10.00,0.00,5.00,9.0,3.0,7.0,6.0,9.0
8374,552,22.0,1,44,2,21,22,13,4,19,...,0.00,15.00,10.00,0.00,5.00,9.0,3.0,7.0,6.0,9.0
8375,552,22.0,1,44,2,21,22,19,10,20,...,0.00,15.00,10.00,0.00,5.00,9.0,3.0,7.0,6.0,9.0
8376,552,22.0,1,44,2,21,22,3,16,21,...,0.00,15.00,10.00,0.00,5.00,9.0,3.0,7.0,6.0,9.0
8377,552,NaN,1,44,2,21,22,2,15,22,...,0.00,15.00,10.00,0.00,5.00,9.0,3.0,7.0,6.0,9.0